### PR TITLE
Reset password

### PR DESCRIPTION
**Pull request by Minglee01**
@grahamgilchrist  Fix for reset password success message translation

### CODE REVIEW

**Comment by grahamgilchrist** [comment]
@Minglee01 Looks good. My only comment is the version number. We are using semver for the versioning on this project. More info here: [http://semver.org/](http://semver.org/)

Since this is technically a bug fix, without changing functionality, it would be counted as a PATCH update in semver terms. This means only the third digit is incremented - so the new version should be 0.5.6 instead of 1.0.0 

If you can update that, this is good to merge :)

**Comment by Minglee01** [comment]
its not backwards compatible though

**Comment by grahamgilchrist** [comment]
The externally facing API/interface is still backwards compatible, since you have only changed lines inside the function which won't affect the input/output. Projects using that directive won't break as it works in exactly the same way, we've just fixed a minor bug.

**Comment by grahamgilchrist** [comment]
Great!

**Pull request merged**
