### PR TITLE
Remove form.pristine check 

### PR DESCRIPTION
**Pull request by Minglee01**
@incuna/js 

Remove prisitine check so that the api can return an error message.

### CODE REVIEW

**Comment by maxpeterson** [comment]
I think this has been deprecated in favour of https://github.com/incuna/angular-user-management

**Comment by Minglee01** [comment]
It has but one of our projects is still using it. I guess we could upgrade but there may be complications??

**Comment by maxpeterson** [comment]
I think the `if (!form.$pristine) {` condition is deliberate.

The approach we have taken elsewhere is to disable / grey out the submit button until the user modifies a field (and the form is no longer `pristine`).

**Comment by Minglee01** [comment]
can close this as we are implementing the solution in a different way.

**Pull request closed without merging**
